# Travis CI config for AssetResizer
language: swift
osx_image: xcode10.1
xcode_project: AssetResizer.xcodeproj

env:
  global:
  - SCHEME=AssetResizer

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -scheme "$SCHEME" test | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email: false
